/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Reporte;

import Vista.*;
import Vista.Pedido.*;
import Vista.*;

/**
 *
 * @author DroKaN
 */
public class Reporte extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    public Reporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jsClientes = new javax.swing.JScrollPane();
        jtClientes = new rojerusan.RSTableMetro();
        btnCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PEDIDOS PARA ENTREGAR");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, 77));

        jsClientes.setBorder(null);

        jtClientes = new rojerusan.RSTableMetro(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtClientes.setFuenteFilas(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtClientes.setGridColor(new java.awt.Color(102, 102, 102));
        jtClientes.setGrosorBordeFilas(0);
        jtClientes.setGrosorBordeHead(0);
        jtClientes.setRowHeight(30);
        jtClientes.getTableHeader().setReorderingAllowed(false);
        jsClientes.setViewportView(jtClientes);

        add(jsClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 210, 1280, 740));

        btnCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px_1.png"))); // NOI18N
        btnCliente.setText("Imprimir");
        btnCliente.setBorder(null);
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setFocusPainted(false);
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px.png"))); // NOI18N
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Al :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, 30));

        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 270, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Del :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 30));

        jDateChooser2.setDateFormatString("d-M-Y");
        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDateChooser2.setMinimumSize(new java.awt.Dimension(28, 28));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 250, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCliente;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jsClientes;
    public rojerusan.RSTableMetro jtClientes;
    // End of variables declaration//GEN-END:variables
}
