/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Reporte;

import Vista.*;
import Vista.Pedido.*;
import Vista.*;

/**
 *
 * @author DroKaN
 */
public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAnio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dtMes = new com.toedter.calendar.JMonthChooser();
        dtAnio = new com.toedter.calendar.JYearChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dtMAnio = new com.toedter.calendar.JYearChooser();
        btnFechas = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        btnMes = new javax.swing.JButton();
        dtFecha = new com.toedter.calendar.JDateChooser();
        dtDel = new com.toedter.calendar.JDateChooser();
        dtAl = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REPORTES");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, 77));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Reporte de pedidos Anual");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, -1, -1));

        btnAnio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAnio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px_1.png"))); // NOI18N
        btnAnio.setText("Imprimir");
        btnAnio.setBorder(null);
        btnAnio.setBorderPainted(false);
        btnAnio.setContentAreaFilled(false);
        btnAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnio.setFocusPainted(false);
        btnAnio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnAnio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px.png"))); // NOI18N
        btnAnio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Año:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Del :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Reporte de pedidos entre fechas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Hasta :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Reporte de pedidos por fecha");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Fecha:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, 30));

        dtMes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(dtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, 30));
        add(dtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Reporte de pedidos mensual");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Mes:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, 30));
        add(dtMAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, 30));

        btnFechas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px_1.png"))); // NOI18N
        btnFechas.setText("Imprimir");
        btnFechas.setBorder(null);
        btnFechas.setBorderPainted(false);
        btnFechas.setContentAreaFilled(false);
        btnFechas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechas.setFocusPainted(false);
        btnFechas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnFechas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px.png"))); // NOI18N
        btnFechas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, -1));

        btnFecha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px_1.png"))); // NOI18N
        btnFecha.setText("Imprimir");
        btnFecha.setBorder(null);
        btnFecha.setBorderPainted(false);
        btnFecha.setContentAreaFilled(false);
        btnFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFecha.setFocusPainted(false);
        btnFecha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFecha.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px.png"))); // NOI18N
        btnFecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, -1, -1));

        btnMes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px_1.png"))); // NOI18N
        btnMes.setText("Imprimir");
        btnMes.setBorder(null);
        btnMes.setBorderPainted(false);
        btnMes.setContentAreaFilled(false);
        btnMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMes.setFocusPainted(false);
        btnMes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Print_50px.png"))); // NOI18N
        btnMes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 460, -1, -1));

        dtFecha.setDateFormatString("dd-MM-yyyy");
        dtFecha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(dtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 290, 30));

        dtDel.setDateFormatString("dd-MM-yyyy");
        dtDel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(dtDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 290, 30));

        dtAl.setDateFormatString("dd-MM-yyyy");
        dtAl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(dtAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 290, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnio;
    public javax.swing.JButton btnFecha;
    public javax.swing.JButton btnFechas;
    public javax.swing.JButton btnMes;
    public com.toedter.calendar.JDateChooser dtAl;
    public com.toedter.calendar.JYearChooser dtAnio;
    public com.toedter.calendar.JDateChooser dtDel;
    public com.toedter.calendar.JDateChooser dtFecha;
    public com.toedter.calendar.JYearChooser dtMAnio;
    public com.toedter.calendar.JMonthChooser dtMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
