/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Pedido;

import Vista.*;

/**
 *
 * @author DroKaN
 */
public class ListaPedido extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    public ListaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jstab = new rojerusan.RSTableMetroBeanInfo();
        txtTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jsClientes = new javax.swing.JScrollPane();
        jtPedidos = new rojerusan.RSTableMetro();
        btnPedido = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(128, 128, 131));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("PEDIDOS");
        add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, 77));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Buscar:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 410, -1));

        jsClientes.setBorder(null);

        jtPedidos = new rojerusan.RSTableMetro(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jtPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPedidos.setFuenteFilas(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtPedidos.setGridColor(new java.awt.Color(102, 102, 102));
        jtPedidos.setGrosorBordeFilas(0);
        jtPedidos.setGrosorBordeHead(0);
        jtPedidos.setRowHeight(30);
        jtPedidos.getTableHeader().setReorderingAllowed(false);
        jsClientes.setViewportView(jtPedidos);

        add(jsClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 210, 1280, 740));

        btnPedido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Missed_Call_50px_2.png"))); // NOI18N
        btnPedido.setText("Nuevo Pedido");
        btnPedido.setBorder(null);
        btnPedido.setBorderPainted(false);
        btnPedido.setContentAreaFilled(false);
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.setFocusPainted(false);
        btnPedido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Missed_Call_50px_1.png"))); // NOI18N
        btnPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jsClientes;
    public rojerusan.RSTableMetroBeanInfo jstab;
    public rojerusan.RSTableMetro jtPedidos;
    public javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
