/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btInicio = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btProductos = new rsbuttom.RSButtonMetro();
        btClientes = new rsbuttom.RSButtonMetro();
        btPedidos = new rsbuttom.RSButtonMetro();
        btReporte = new rsbuttom.RSButtonMetro();
        btZonas = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        btMinim = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btInicio.setForeground(new java.awt.Color(128, 128, 131));
        btInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        btInicio.setText("Inicio");
        btInicio.setColorHover(new java.awt.Color(204, 204, 204));
        btInicio.setColorNormal(new java.awt.Color(204, 204, 204));
        btInicio.setColorPressed(new java.awt.Color(204, 204, 204));
        btInicio.setColorTextHover(new java.awt.Color(128, 128, 131));
        btInicio.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btInicio.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btInicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btInicio.setIconTextGap(25);
        pnlMenu.add(btInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 50));

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("MENU");

        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 258, -1));

        btProductos.setBackground(new java.awt.Color(239, 238, 244));
        btProductos.setForeground(new java.awt.Color(128, 128, 131));
        btProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos.png"))); // NOI18N
        btProductos.setText("Productos");
        btProductos.setColorHover(new java.awt.Color(204, 204, 204));
        btProductos.setColorNormal(new java.awt.Color(239, 238, 244));
        btProductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btProductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btProductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btProductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btProductos.setIconTextGap(19);
        pnlMenu.add(btProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        btClientes.setBackground(new java.awt.Color(239, 238, 244));
        btClientes.setForeground(new java.awt.Color(128, 128, 131));
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setColorHover(new java.awt.Color(204, 204, 204));
        btClientes.setColorNormal(new java.awt.Color(239, 238, 244));
        btClientes.setColorPressed(new java.awt.Color(204, 204, 204));
        btClientes.setColorTextHover(new java.awt.Color(128, 128, 131));
        btClientes.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btClientes.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btClientes.setIconTextGap(25);
        pnlMenu.add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 50));

        btPedidos.setBackground(new java.awt.Color(239, 238, 244));
        btPedidos.setForeground(new java.awt.Color(128, 128, 131));
        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.setColorHover(new java.awt.Color(204, 204, 204));
        btPedidos.setColorNormal(new java.awt.Color(239, 238, 244));
        btPedidos.setColorPressed(new java.awt.Color(204, 204, 204));
        btPedidos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btPedidos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btPedidos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPedidos.setIconTextGap(19);
        pnlMenu.add(btPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 50));

        btReporte.setBackground(new java.awt.Color(239, 238, 244));
        btReporte.setForeground(new java.awt.Color(128, 128, 131));
        btReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        btReporte.setText("Reporte");
        btReporte.setColorHover(new java.awt.Color(204, 204, 204));
        btReporte.setColorNormal(new java.awt.Color(239, 238, 244));
        btReporte.setColorPressed(new java.awt.Color(204, 204, 204));
        btReporte.setColorTextHover(new java.awt.Color(128, 128, 131));
        btReporte.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btReporte.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btReporte.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btReporte.setIconTextGap(19);
        btReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteActionPerformed(evt);
            }
        });
        pnlMenu.add(btReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 260, 50));

        btZonas.setBackground(new java.awt.Color(239, 238, 244));
        btZonas.setForeground(new java.awt.Color(128, 128, 131));
        btZonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Map_Marker_50px_1.png"))); // NOI18N
        btZonas.setText("Zonas");
        btZonas.setColorHover(new java.awt.Color(204, 204, 204));
        btZonas.setColorNormal(new java.awt.Color(239, 238, 244));
        btZonas.setColorPressed(new java.awt.Color(204, 204, 204));
        btZonas.setColorTextHover(new java.awt.Color(128, 128, 131));
        btZonas.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btZonas.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btZonas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btZonas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btZonas.setIconTextGap(25);
        pnlMenu.add(btZonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 50));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AquaSae");

        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Delete_25px.png"))); // NOI18N
        btCerrar.setBorder(null);
        btCerrar.setBorderPainted(false);
        btCerrar.setContentAreaFilled(false);
        btCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar.setFocusPainted(false);
        btCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Delete_25px_1.png"))); // NOI18N

        btMinim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Subtract_25px_1.png"))); // NOI18N
        btMinim.setBorder(null);
        btMinim.setBorderPainted(false);
        btMinim.setContentAreaFilled(false);
        btMinim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMinim.setFocusPainted(false);
        btMinim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Subtract_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 718, Short.MAX_VALUE)
                .addComponent(btMinim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMinim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        //x = evt.getX();
        //y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //Point mueve = MouseInfo.getPointerInfo().getLocation();
        //this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btCerrar;
    public rsbuttom.RSButtonMetro btClientes;
    public rsbuttom.RSButtonMetro btInicio;
    public javax.swing.JButton btMinim;
    public rsbuttom.RSButtonMetro btPedidos;
    public rsbuttom.RSButtonMetro btProductos;
    public rsbuttom.RSButtonMetro btReporte;
    public rsbuttom.RSButtonMetro btZonas;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    public static javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
